version: '3.8'

services:
  postgres:
    user: root
    image: postgres:latest
    container_name: ChatAssistant 
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
      PGDATA: 'var/lib/pg_data'
    ports:
      - '5432:5432'
    networks:
      - local
networks:
  local: